### PR TITLE
MLJ's tidying up of pipeline and documentation

### PR DESCRIPTION
**Pull request by befriendabacterium**

### CODE REVIEW

**Comment by befriendabacterium** [comment]
Conflict in taxa_wsp_readyforanalysis.csv is because it should have 1454 ASVs, instead of 1480 ASVs, I think. I assume your downstream analysis works with the 1480 version because it uses the ASV names rather than order, so doesn't matter if there are some redundant ASVs in taxa table. But if possible to use 1454 ASV version would recommend for tidyness.

**Comment by befriendabacterium** [comment]
Re the other conflict, I assume that is because we both made changes on that script since I forked the repo.

**Review by apascualgarcia — APPROVED** [review]

**Review by apascualgarcia — APPROVED** [review]
Thanks for these changes and well done, I think it makes sense the renaming you proposed. There still is a conflict to address because I do not hardcode names of files within read/write functions (I tend to use variables defined at the beginning of the scripts) but it is easy to assess

**Review by apascualgarcia — APPROVED** [review]

**Review by apascualgarcia — APPROVED** [review]

**Comment by befriendabacterium** [comment]
Cool, looks like you've handled it all OK! Let me know if you need anything else from me!
________________________________

**Pull request merged**
